#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#
def miniMaxSum(arr):
    sum1=0
    sum2=0
    arr.sort()
    sum1=sum(arr[:4])
    sum2=sum(arr[-4:])
    print(sum1,sum2)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
