#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#
def plusMinus(arr):
    c1=0
    c2=0
    c3=0 
    for i in arr:
        if(i>0):
            c1=c1+1
        elif(i<0):
            c2=c2+1
        else:
            c3=c3+1
    print(round(c1/n,6))
    print(round(c2/n,6))
    print(round(c3/n,6))   
n = int(input().strip())
arr = list(map(int, input().rstrip().split()))
plusMinus(arr)
