#!/bin/python3

import math
import os
import random
import re
import sys


def timeConversion(s):
    # Write your code here
    if(s[8:]=='PM'):
        s1=0
        s1=int(s[0:2])+12
        s=str(s1)+str(s[2:11])
        if s[0:2]=='24':
            s='12'+s[2:11]
        elif s[0:2]=='18':
            s='06'+s[2:11]
        return s[:8]
    else:
        if s[0:2]=='12':
            s='00'+s[2:11]
        return s[0:8]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()

    
    
